tap "homebrew/bundle"
tap "homebrew/core"

# we need these two for the installation
brew "zsh"
brew "git"

# programming tools
brew "python3"
brew "ruby"
brew "node"
brew "nvm"
brew "yarn"

# some fun command line tools 
brew "cowsay"
brew "sl"
brew "fortune"
brew "cmatrix"
